\clearpage
# Figures


<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```


<!-- ====================================================================== -->
<!-- *************************     Biology     **************************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "AG_plot_lines_parameters.png"), 
caption = "Observed length-at-age by data source and sex. Lines indicate fits to the von Bertalanffy growth equation, with parameter estimates provided in the bottom right corner of the figure",
label = 'len-age-data')
```	

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio1_sizeatage.png"), 
caption = "Length at age in the beginning of the year in the ending year of the model",
label = 'len-age-ss')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Age_error_plot.png"), 
caption = "Agein error matrix (age by standard deviation) values by source. The commercial and recreational matrices are based on inter-reader comparisons",
label = 'age-error')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of  length",
label = 'maturity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(mod_loc, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity as a function of length",
label = 'fecundity')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(bio_fig_loc, "Mdensityplots_OR_vermilion.png"), 
caption = "Composite natural mortality distriubtion for $S. hopkinsi$ using four longevity estimators each with a SD = 0.2 presuming a lognomral error distibution",
label = 'M_composite_dists')
```
